apiVersion: v1
kind: Service
metadata:
  name: api-srv
  namespace: app-api
  labels:
    app: api-master
    tier: backend
spec:
  ports:
    - name: app
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: api-master
    tier: backend