apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
  namespace: app-api
  labels:
    app: nginx-master
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-master
    tier: frontend