apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: app-api
  labels:
    app: postgres-master
    tier: backend
type: Opaque
data:
  user: dXNlcg==
  password: cGFzc3dvcmQ=
  database: ZGF0YWJhc2U=